apiVersion: v1
kind: Service
metadata:
  name: service-frontend
  labels:
    run: frontend
spec:
  type: LoadBalancer
  ports:
    - name: "8100"
      port: 8100
      targetPort: 80
  selector:
    run: frontend
